name: Android CI

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install git tree
      run: |
        sudo apt-get update
        sudo apt-get -y install git tree
    - name: clone code
      run: |
        git clone --depth=1 https://github.com/gedoor/legado.git /opt/legado
    - name: Build with Gradle
      run: |
        cd /opt/legado
        chmod +x gradlew
        ./gradlew assembleRelease 
    - name: tree view
      run: tree ./app/build
