# This is a basic workflow to help you get started with Actions

name: Schedule Run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    
  schedule:
    - cron: '0 */12 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest
    env:
      check: ${{ false }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: install git
      run: |
        sudo apt-get update
        sudo apt-get -y install git
        echo "check:$check"
        check = ${{ true }}
        echo "check:$check"
    - name: Check latest tag
      run: bash $GITHUB_WORKSPACE/schedule.sh
     
